export const GET_MEMBER_DETAIL_REQUESTED = 'GET_MEMBER_DETAIL_REQUESTED';
export const GET_MEMBER_DETAIL_SUCCESS = 'GET_MEMBER_DETAIL_SUCCESS';
export const GET_MEMBER_DETAIL_FAILURE = 'GET_MEMBER_DETAIL_FAILURE';
